FROM ghcr.io/ministryofjustice/hmpps-python:python3.13-alpine AS base

# initialise uv
COPY pyproject.toml .
RUN uv sync

# Copy the Python goodness
COPY ./*.py .

CMD [ "uv", "run", "python", "-u", "Dcomponent_dependencies_discovery.py" ]
