apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmpps-component-dependencies-discovery
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjobs.componentDependencyDiscovery }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          containers:
          - name: hmpps-component-dependencies
            image: {{ .Values.imagePython.repository }}:{{ .Values.imagePython.tag }}
            command: ["uv", "run", "python", "-u", "/app/components_dependencies_discovery.py"]
            securityContext:
              capabilities:
                drop:
                - ALL
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
{{ include "deployment.envs" . | nindent 12 }}
          restartPolicy: Never
