
image:
  repository: ghcr.io/ministryofjustice/hmpps-component-dependencies
  tag: xxx

appinsightEnvs: ["DEV", "PREPROD", "PROD"]

cronjobs:
  updateDependencyInfo: 0 */6 * * *

generic-prometheus-alerts:
  targetApplication: hmpps-component-dependencies
  ingressAlertsEnabled: false

namespace_secrets:
  hmpps-envoy-https-proxy-env:
    HTTP_PROXY: "HTTP_PROXY"
    HTTPS_PROXY: "HTTPS_PROXY"
    NO_PROXY: "NO_PROXY"
    http_proxy: "HTTP_PROXY"
    https_proxy: "HTTPS_PROXY"
    no_proxy: "NO_PROXY"
