FROM ghcr.io/ministryofjustice/hmpps-python:python3.13-alpine AS base

# initialise uv
COPY scripts/pyproject.toml .
RUN uv sync

# Copy the Python goodness
COPY scripts/*.py .

CMD [ "uv", "run", "python", "-u", "components_dependencies_discovery.py" ]
