---
# Per environment values which override defaults in hmpps-component-dependencies/values.yaml

redis:
  secretName: elasticache-redis

apis:
  serviceCatalogue:
    url: https://service-catalogue-dev.hmpps.service.justice.gov.uk

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-nonprod

namespace_secrets:
  hmpps-envoy-https-proxy-env:
    HTTP_PROXY: "HTTP_PROXY"
    HTTPS_PROXY: "HTTPS_PROXY"
    NO_PROXY: "NO_PROXY"
    http_proxy: "HTTP_PROXY"
    https_proxy: "HTTPS_PROXY"
    no_proxy: "NO_PROXY"
